# Part1

### Q1
  A: It will print "values added: 20". 

### Q2
  A: It will print "final result: 20".
  
### Q3
  A: It will print "values added: 20". 

### Q4 
  A: We would get an error because since we are using a let variable, we 
  only have access to it in the block it is declared, and this print statement
  is trying to use it outside the block it was declared.
 
### Q5
  A: A: It will print "values added: 20". 
  
### Q6
  A: We would get an error because since we are using a const which has the same
  rules as the let variable, scoping wise. We are not able to reference it after
  we outside the block it was declared in. And this print statements tries to do 
  that, which gives us an error.
  
 ## End of Part 1
